on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-assets:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Setup volta
        uses: volta-cli/action@v4

      - name: Install Dependencies
        run: yarn
      - name: Update Assets
        run: node scripts/scrape-fandom.js
      - name: Force a commit
        run: touch test.txt && echo "test" >> test.txt
      - name: Commit and Push if changed
        uses: EndBug/add-and-commit@v9
        with:
          message: "chore: update assets [${{ github.sha }}]"
